### ISSUE TITLE
Search nearest target in regular intervals?

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkeyprojects/Sentinel#153]
Is it possible to let them search the nearest target in regular intervals? I think now they search the nearest target when they hit their target. So sometimes happens this:
He chase a target in large distance. And he doesn´t change to a target that is right next to him,  because he doesn´t search a new target until he hit his current target.

**Comment by mcmonkey4eva** [comment]
an active target is considered higher priority than a passing target by current configuration

**Comment by Firemonkey08** [comment]
Ah ok. Good to know. We are testing what happens when two targets attack him. Then both should be active targets, shouldn´t be? The choose and switch of an archer is good, he takes the nearest one. But scrappers switch rarley the target, when two targets attack him and one is nearer. Didn´t find out why since yet.

**Comment by mcmonkey4eva** [comment]
My original post above explained why: `an active target is considered higher priority than a passing target by current configuration`

In the interest of improving the Sentinel combat AI in this regard, I've made it so NPCs will swing melee weapons at any targets that get too close if the NPC cannot hit the main target (eg because the NPC needs to run farther towards it before it's in range).

This improvement is available in Sentinel build DEV-226+

**Comment by Firemonkey08** [comment]
nice 👍
