### ISSUE TITLE
Respawn in other places(maybe after server restart)

### ISSUE THREAD

**Issue by DenisJ9798** [mcmonkeyprojects/Sentinel#284]
Discovered the problem with the NPC.
Once you place an NPC in a specific location, it will stay there. But over time, he disappears and finds himself in a completely different area of the map.
I can't understand the reason for such NPC behavior.
Previously this was on one NPC. How, under what conditions he did it, I do not know and do not know how long it took him to do it.(independently move from place to place).
Only yesterday I found out that I moved all the NPCs that were previously placed on the map. All the NPCs moved to the same area of the map without my knowledge.

**Comment by mcmonkey4eva** [comment]
`All the NPCs moved to the same area of the map without my knowledge.`
That has been known to happen in a few cases due to plugin conflicts with things like WorldGuard with `entry: deny` set (as it denies the NPCs entry to wherever they were at, and flings them back to the spawn area or other weird places) - the main solution in that case is to update WG to latest 7.x version (they've released a patch recently for that). If a different plugin is causing that same effect, contact that plugin's author.

If you can also happen in some cases if you have NPCs that have the same name as an actual player (as some plugins will teleport the _NPC_ to the player's location for whatever weird reason) - the solution there is to just add a color code onto the NPC's name, eg `/npc create &bBob`.

If neither of these apply, please reply below with more details (where were the NPCs? Where are they now? What plugins are you running? What is the output of `/version` and `/version sentinel` and `/version citizens`?)

**Comment by DenisJ9798** [comment]
> `All the NPCs moved to the same area of the map without my knowledge.`
> Известно, что это происходило в нескольких случаях из-за конфликтов плагинов с такими вещами, как WorldGuard с `entry: deny`set (поскольку он запрещает вход NPC туда, где они были, и отбрасывает их обратно в область возрождения или в другие странные места) - основное решение в этом случае необходимо обновить WG до последней версии 7.x (недавно для этого был выпущен патч). Если другой плагин вызывает тот же эффект, свяжитесь с его автором.
> 
> Если вы также можете случиться в некоторых случаях, если у вас есть неигровые персонажи с тем же именем, что и у реального игрока (так как некоторые плагины будут телепортировать _неигрового персонажа_ в локацию игрока по какой-то странной причине) - решение - просто добавить цветной код на имя NPC, например `/npc create &bBob`.
> 
> Если ни один из них не подходит, пожалуйста, ответьте ниже с более подробной информацией (где находились неигровые персонажи? Где они сейчас? Какие плагины вы используете? Каковы результаты `/version`и `/version sentinel`и `/version citizens`?) Эти последние несколько вопросов находятся в выбранном вами шаблоне проблемы. по какой-то причине удалить вместо следующего.

I removed the entry flag, to wg7 I can't update as I use the version of spigot 1.12.2 wg 6.2.2

**Comment by DenisJ9798** [comment]
> `All the NPCs moved to the same area of the map without my knowledge.`
> Известно, что это происходило в нескольких случаях из-за конфликтов плагинов с такими вещами, как WorldGuard с `entry: deny`set (поскольку он запрещает вход NPC туда, где они были, и отбрасывает их обратно в область возрождения или в другие странные места) - основное решение в этом случае необходимо обновить WG до последней версии 7.x (недавно для этого был выпущен патч). Если другой плагин вызывает тот же эффект, свяжитесь с его автором.
> 
> Если вы также можете случиться в некоторых случаях, если у вас есть неигровые персонажи с тем же именем, что и у реального игрока (так как некоторые плагины будут телепортировать _неигрового персонажа_ в локацию игрока по какой-то странной причине) - решение - просто добавить цветной код на имя NPC, например `/npc create &bBob`.
> 
> Если ни один из них не подходит, пожалуйста, ответьте ниже с более подробной информацией (где находились неигровые персонажи? Где они сейчас? Какие плагины вы используете? Каковы результаты `/version`и `/version sentinel`и `/version citizens`?) Эти последние несколько вопросов находятся в выбранном вами шаблоне проблемы. по какой-то причине удалить вместо следующего.

All NPCs spawn in spawnpoint if it is worldguard 6.2.2, how to fix it?

**Comment by mcmonkey4eva** [comment]
uh, update your server to 1.13? :D
