### ISSUE TITLE
Target Option: Equipped Items (similar to helditem)

### ISSUE THREAD

**Issue by LordTurnip** [mcmonkeyprojects/Sentinel#307]
Creating the ability for sentinels to ignore players based on the armor/equipment they are wearing, which could or could not be limited to just armors, or even specifically named player heads or items.

**Comment by axemwa** [comment]
Probably re-name the title to Feature Request to add ability to make sentinels ignore/avoid/target players that are wearing certain equipped armor items.

Cause atm it looks like you're saying that sentinels are not able to wear certain things ppl might get confused by the way you've stated it thinking it might be a bug

**Comment by SXRWahrheit** [comment]
We discussed this on Discord, Monkey knows what it is.

**Comment by axemwa** [comment]
K just doesn't look right, nvm

**Comment by mcmonkey4eva** [comment]
- I removed the stray junk from the opening post there (corrupt copies of server version details... which isn't even need in the first place for a feature request lol)

So, features to add:
- Equipped Item target type (similar to held item)
- Make the item matches able to check more advanced detail (item display name for example, rather than only the material)
- Probably also add target types for offhandheld and inventory contains.

**Comment by SXRWahrheit** [comment]
nbt data tho 👀

**Comment by mcmonkey4eva** [comment]
Not possible within Sentinel (Sentinel does not use NMS)

**Comment by SXRWahrheit** [comment]
Bummer.

**Comment by axemwa** [comment]
Looking forward to the new features good luck :)

**Comment by mcmonkey4eva** [comment]
Made a more  powerful item matcher - you can do `offhand`, `equipped`, and `in_inventory` now. You can also specify `name` or `lore` instead of standard material matching. See readme for more detail
