### ISSUE TITLE
Sentinel NPCs chasing a target seem to pause when close

### ISSUE THREAD

**Issue by Ferocimo** [mcmonkeyprojects/Sentinel#335]
The output of command `/version` on my server is: **Paper version git-Paper-229 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1921)**
The output of command `/version sentinel` on my server is: **version 2.0.1-SNAPSHOT (build 343)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(PLEASE FILL IN)**

Hello,

We noticed several issues with latest versions of Citizens, Sentinel and Minecraft. 

The first one is that Sentinels can't move in water at all, again. This issue was previously fixed but it seems to be back. We have set "avoidwater" to true but players often just push sentinels in water and since they can't get out, it's easy kill.

The second one is that Sentinels seem to mimic player movements, which means they "pause" whenever the player pauses and then resume chasing. In general, Sentinels very often pause mid chase for a moment, which makes their behavior very unrealistic and more easily predictable.

The third one is that they have troubles with carpets. If a room has carpets, the sentinel seems to think that these are "full blocks" the player walks in and they seem to think they can't pass. So they don't move at all. See below : 
http://www.noelshack.com/2020-18-5-1588365487-2020-05-01-22-36-25.png

Thank you for your time.

**Comment by mcmonkey4eva** [comment]
water and carpets are Citizens issues, not Sentinel

The pausing _might_ be a Sentinel issue. That can happen if the Sentinel gets into attack range of the player and then the player moves away... once it's in range it's not going to continue chasing because it's already close enough. If there's more to it than that, please explain further and/or post a video to demonstrate what's happening.

**Comment by Ferocimo** [comment]
Unfortunately we can't use new-finder because it causes massive performance issues. What should we do ?

For the pausing : https://streamable.com/cyxmc4
I'm not sure it's a range issue, as you can see at the beggining of the video it pauses right away with quite a distance from the player.

**Comment by mcmonkey4eva** [comment]
That looks like it **is** a range thing - it's within attack range of the player when it stops, but the player keeps moving, and it stays stopped for a bit too long and so falls behind.
Do you have `workaround entity chase pathfinder` enabled in your config?

**Comment by Ferocimo** [comment]
Okay I see.
No it's disabled.

**Comment by mcmonkey4eva** [comment]
Try build 344+ from https://ci.citizensnpcs.co/job/Sentinel/ , and specifically enable `workaround entity chase pathfinder`.
I think it should be better about it. The basic idea, is it tracks the player's motion to predict where they're going, and thus set the target as where the player *will* be instead of where they *are*. This should make it much less likely to pause while chasing a moving player.

**Comment by Ferocimo** [comment]
It seems fully functionnal now, thank you. Now we just have to wait for the Citizens improvement to new-finder to fix the rest...
