### ISSUE TITLE
Issue with NPC taking damage

### ISSUE THREAD

**Issue by SergeMedievus** [mcmonkeyprojects/Sentinel#337]
**The output of command `/version` on my server is:**
CraftBukkit version git-Bukkit-a6f8093 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**The output of command `/version citizens` on my server is:** 
Citizens version 2.0.26-SNAPSHOT (build 1921)
**The output of command `/version sentinel` on my server is:** 
Sentinel version 2.0.1-SNAPSHOT (build 327)
**`Sentinel/config.yml` file is:**
https://pastebin.com/cZuqc3rP
**Plugins:**
WorldEdit, SkinsRestorer, Timber, BlockLocker, PermissionsEx, Vault, WorldGuard, Citizens, ChestShop, Quests, AreaShop, Essentials (+Protect, Spawn & Chat), Jobs, Sentinel

Hey,
I'm having an issue with NPCs taking damage.
**Issue:**
- NPC vs Player: NPC doesn't take damage, whilst player does,
- NPC vs Monster: NPC doesn't take damage, whilst monster does,
- NPC vs NPC: both NPCs take damage (and can kill one another) whilst in combat with one another.

**What I tried:**
- Setting up a town guard using the manual - made sure its vulenrable,
- Setting up a test NPC (without any config) - made sure its vulnerable,
- Played with config file per manual and then per my own thinking,
- Used CitizensGUI plugin to check if they are (for sure) vulnerable,
- Tried hitting them in both WorldGuard (no-pvp) areas and outside of them (pvp).

What I want to achieve is obviously NPCs taking damage from any combat they are in.

As a note - I'm running CraftBukkit, instead of Spigot, since I had issues with economy plugins.

Tried googling and improvising and it's still not working, so thanks in advance!

**Comment by mcmonkey4eva** [comment]
`As a note - I'm running CraftBukkit, instead of Spigot, since I had issues with economy plugins.`
That ain't gonna work.
CraftBukkit hasn't been a thing since 2014 when the Bukkit project shut down.

Use Spigot or Paper.
If problems continue, check if you have anything else blocking PvP - ideally have another player join and make sure you can hit them.
If PvP doesn't seem blocked at all, check for a plugin conflict (ie basically test whether it works if you remove plugins). See also https://wiki.citizensnpcs.co/Plugin_Conflict

If none of that works, join the Discord @ https://discord.gg/Q6pZGSR and ask for help in `#sentinel`.
