### ISSUE TITLE
Sentinel refuses to chase/attack

### ISSUE THREAD

**Issue by Tyloon1e** [mcmonkeyprojects/Sentinel#355]
The output of command `/version` on my server is: **[Server] INFO This server is running Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **[Server] INFO Citizens version 2.0.27-SNAPSHOT (build 2188)**
The output of command `/version sentinel` on my server is: **[Server] INFO Sentinel version 2.2.0-SNAPSHOT (build 376)**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **https://pastebin.com/raw/CMcAi5uG**

My Sentinel NPC refuses to chase me! It waits until I get close enough to kill me, what do I do?
Showcase: https://gyazo.com/3ac30d3de3f9cccb2d7ac98864f47c4c
Citizens saves.yml: https://pastebin.com/raw/R7cEmhGg

**Comment by mcmonkey4eva** [comment]
Nothing stands out as clearly wrong from the saves data on the NPC. The gif looks like a too-short chaserange value, but in the saves it's 70 so that's not it (unless the saves file doesn't come from the same setup as where that gif was recorded?).

So, steps to try, more or less in order of significance to try:

- Please test on Spigot or Paper, not Tuinity or other forks.
- Check your logs for error messages. Any error message, even if it doesn't *seem* related, is potentially relevant. A lot of errors have weird side effects.
- Try removing one of the two path points on that NPC (so it's guarding a single point, rather than an entire path). If that fixes it, there's probably a bug to be fixed, so please do reply to let me know if that happened and I'll look into that angle further.
- If none of the above resolve the problem: Enable `/sentinel debug`, then replicate the problem (redo the demonstration you recorded as a gif), then pastebin the full `logs/latest.log` file and link that here.

**Comment by mcmonkey4eva** [comment]
Update: The underlying Citizens issue was fixed in build 2189 https://ci.citizensnpcs.co/job/Citizens2/
