### ISSUE TITLE
Sentinel slow pathing + hitting with shield/not blocking

### ISSUE THREAD

**Issue by SlyyJacob** [mcmonkeyprojects/Sentinel#367]
Please fill in the three slots below (with EXACT copy-pastes or screenshots!)...
-->

The output of command `/version` on my server is: **(PLEASE FILL IN)**
Paper git-Paper-88 (1.17.1)
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
2.0.28 - snapshot (2341)
The output of command `/version sentinel` on my server is: **(PLEASE FILL IN)**
2.3.0 - snapshot (416)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(PLEASE FILL IN)**
https://pastebin.com/naJKSrPL

https://pastebin.com/pcn1RH9d
https://streamable.com/4ddscf

I have two issues with sentinels - first they move slowly, as seen on the video, when pathing. Second they don't block with shield but instead use it to hit with it.

**Comment by mcmonkey4eva** [comment]
- You have the items backwards - shield should be in offhand, not mainhand
- You also move slow yourself when blocking with a shield, it's a vanilla mechanic

**Comment by SlyJacobTheBeast** [comment]
![2021-07-08 10_34_42](https://user-images.githubusercontent.com/36818957/124890264-2749a580-dfd8-11eb-9e02-66c7692589a8.jpg)
I don't think I have it wrong? Unless shield icon is supposed to indicate main hand and sword off hand.

**Comment by mcmonkey4eva** [comment]
Might be a 1.17 bug with the `PlayerAnimation` class in Citizens? 0.o

**Comment by SlyJacobTheBeast** [comment]
Might be related, sentinels shooting a bow don't play shooting animation either, just punch animation and the arrow flies out.

**Comment by SlyJacobTheBeast** [comment]
To add to the slow pathing, here is a sentinel holding bow and he's moving the same slow-mo walk like an npc with a shield. https://streamable.com/1xulqc

**Comment by nicoandthe9rs** [comment]
is there a way to fix the shields?

**Comment by mcmonkey4eva** [comment]
Can't replicate slow movement at all. When the NPC is holding a shield, it slows down to block, when not holding a shield, it moves fast.
It goes a little funky if you remove the shield from an NPC while it's aggro, but it's fine again after a respawn. I suspect this the reason you were able to get a video of the NPC moving slow without a shield - you removed the shield just before you started recording - if that's wrong... well idk?

If not the shield thing, it's possible if you update Paper, Citizens, and Sentinel, the slow movement will go away for you.
I've also noticed that the default speed value in the config was being misread as `1.0` instead of `1.5`, and have corrected that (1.0 = walk speed, 1.5 = sprint speed. Essentially NPCs were meant to be sprinting when attacking, but that was turned off by mistake - this could've been manually enable at any time via `/sentinel speed 1.5`, just the default was missing).
If none of that's it, and an NPC that's never held a shield on updated versions is still slow... I really don't know. That shouldn't happen. Last remaining guesses at that point would be a mixup in the Citizens config or that NPC's configuration or an error in the logs.

Regarding the punching instead of blocking, that turns out to actually be a Citizens issue caused by the 1.17 update, so I've reposted it there: https://github.com/CitizensDev/Citizens2/issues/2633

**Comment by SlyyJacob** [comment]
@mcmonkey4eva Okay thanks for all the work on this!

I have managed to find the cause of this today after all. For some reason, and maybe you will have more idea of where that comes from, the speedmodifier in navigator was set to speedmodifier: '0.6000000238418579'. Which caused the slow movement even though they had citizen and sentinel movespeed set to 1+. I am not sure if that's something I've messed up early on, because it's a number I would certainly not set myself manually.

**Comment by mcmonkey4eva** [comment]
`0.6` is the value that gets used for shield blocking movement speed. This value shouldn't in theory persist ever, even if you bug it, as it uses the temporary (local) navigator parameters, not the global/default params... however I think it might be possible that the default might get mistakenly modified if pathfinding fails while holding a shield? The above commit will catch and block that from happening if it can/does.
I believe if you just `/npc speed 1` on that NPC it should set it back.
