### ISSUE TITLE
Support finding player behind wall

### ISSUE THREAD

**Issue by skbeh** [mcmonkeyprojects/Sentinel#388]
It would be great if there is an option that allows the bot finds players behind wall.

**Comment by mcmonkey4eva** [comment]
If you're an API user, you can edit boolean `ignoreLOS`. This value isn't currently exposed to normal in-game command users as it doesn't really seem like a thing anyone would want except as part of some other customized code they're tacking in alongside it

**Comment by skbeh** [comment]
The option works great!
By the way, is it possible to let the bot automatically break the obstacle on the path to enemy?

**Comment by mcmonkey4eva** [comment]
That unfortunately is not a feature, nor a planned one.
I think if you're willing to try to go about implementing it yourself, the main thing you'd have to do is inject into the Citizens pathfinder code, tell it that *every* block is passable rather than just air/etc, and add a stage for breaking blocks as relevant. There's code in Citizens that does this already specifically for doors (it can be set to automatically open them) so if you find that code, you just gotta match it, but for every block.
