### ISSUE TITLE
WeaponMechanics Support

### ISSUE THREAD

**Issue by CJCrafter** [mcmonkeyprojects/Sentinel#390]
Hello,

I am one of the developers for [WeaponMechanics](https://www.spigotmc.org/resources/weaponmechanics-guns-in-minecraft-1-9-4-1-19-3.99913/). WeaponMechanics is a fully-featured replacement for CrackShot, and is quite simply better. I've had quite a few requests to add sentinels support.

The plugin is quite similar to CrackShot. One of the changes that you may care about is that ANY entity (not just players) can shoot a weapon.

Here are some of our helpful API methods:
1. [Generate a weapon](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/WeaponMechanicsAPI.java#L107-L111)
2. [Shoot a weapon from config](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/WeaponMechanicsAPI.java#L250-L261)
3. [MythicMobs shooting weapons](https://github.com/WeaponMechanics/MechanicsMain/blob/master/WeaponMechanics/src/main/java/me/deecaad/weaponmechanics/lib/MythicMobsWeaponShootSkill.java#L16)

I don't mind making a PR if you point me in the right direction. Thanks!

**Comment by mcmonkey4eva** [comment]
If you don't mind writing the code for it yourself, you might prefer to write the integration on your side rather than into Sentinel.

The entirety of Sentinel-Crackshot support is this one class: https://github.com/mcmonkeyprojects/Sentinel/blob/master/src/main/java/org/mcmonkey/sentinel/integration/SentinelCrackShot.java

You might prefer to reference QualityArmory's work: https://github.com/ZombieStriker/QualityArmory/blob/master/src/main/java/me/zombie_striker/qg/npcs_sentinel/SentinelQAHandler.java
They started from the crackshot example too and took it further

API docs @ https://github.com/mcmonkeyprojects/Sentinel#integrating-your-plugin-with-sentinel

**Comment by CJCrafter** [comment]
Thanks for the suggestions! The issue is now tracked at [255](https://github.com/WeaponMechanics/MechanicsMain/issues/255)
