### ISSUE TITLE
NPCs shooting arrows without Bow

### ISSUE THREAD

**Issue by Venlious** [mcmonkeyprojects/Sentinel#68]
I'd like to see the ability to have Sentinel NPCs shoot arrows without holding a bow. This way the NPC could hold something else in their hand, which could be textured differently using a resource pack - without using a bow.

**Comment by mcmonkey4eva** [comment]
Hello, I've been ignoring this issue for 2 years now, largely due to just being too busy to spend the time build every feature, especially the more complex ones (including this one, as I'm not particularly sure how to appropriately structure it with a good balance of "just working" and being sufficiently customizable to work with most server setups that might want something like this).

I think this feature would be great for a PR if anyone out there with development skill wants to try.

It also can be done externally using things like CrackShot (Sentinel natively integrates CrackShot).

**Comment by mcmonkey4eva** [comment]
Hey, sorry for taking literally three years to do this, but uh... added :D

New command: `/sentinel weaponredirect MATERIAL_ONE MATERIAL_TWO`
So you can do `/sentinel weaponredirect wooden_sword bow` and it will start shooting arrows out of a wood sword!
