### ISSUE TITLE
Using Shields

### ISSUE THREAD

**Issue by MatheMaddox** [mcmonkeyprojects/Sentinel#70]
Let NPCs block explosions and deflect arrows with shields from minecraft 1.9

**Comment by xBiscuit** [comment]
Please add this ^^ Makes citizens able to defend much more smartly 👍

**Comment by Firemonkey08** [comment]
I would have an idea to code that, but i dont find a command to make an Entity blocking or raise his hands. There are only the checks isBlocking and isHandRaised...

**Comment by mcmonkey4eva** [comment]
Would definitely have to use the Citizens animation engine for that. Also a lot of clever timing logic to make shield blocking feel reasonable
(IE, an NPC shouldn't just auto block everything, it should only block things it 'sees coming')

**Comment by Formula350** [comment]
Not sure if this was your train of thought there, and keeping in mind I am unfortunately not a coder, but surely there must be something in the MC code for determining if an entity is facing their attacker? If so, then how I'd accomplish this would be to determine: 
If attacker in front of NPC
 Then chance to block incoming attack is 80%

If attacker is +/- 90deg to NPC
 Then chance to block incoming attack is 50%

If attacker is behind NPC
 Then chance to block incoming attack is 5%

From there, assign the Shield damage reduction, which I think should be a static value and not a % of attack. Therefore if it's set to 10 damage and an attack deals 20, on a successful block only 10dmg will pass on to the Armor check. If NPC has a value set for armor, it does whatever routine you already have in place and the remainder is delt to the NPC. Otherwise, if no armor value set, that 10dmg would be passed to the NPC.

On top of that, you could up the complexity by adding a further variable of whether it's Melee, Piercing (arrow) or Explosive. Where say the above is for Melee, and if Piecing, has an increased chance to deflect. If explosive, would reduce the static protection value by a percent (25%?) **and** deal knockback, all to simulate the concussive aspect of the explosion.

**Comment by rotus1122334455** [comment]
Is this added ? I Really want my Npc Guards USE Shields and protect from arrows etc ...

Is this added ?

**Comment by mcmonkey4eva** [comment]
This would be a neat feature for anyone with a bit of development skill to try to add in a pull request.

I'm a bit cautious about trying to add it myself as I suspect it will take a fair amount of time investment to get it right.

**Comment by mcmonkey4eva** [comment]
Sorry for taking literally three years to do this, but uh... added :D

Sentinel NPCs equipped with a shield in their offhand will now use it to block threats.
They will only block threats they see coming (ie active targets that are directly ahead of them and either are close or are holding a ranged weapon).
When blocking, their movement speed will be lowered, and they will take exactly half damage from all weapons except piercing arrows. This is of course a very cheap basic approximation... in part because I don't really know how the internal logic for shields actually works tbh. But also, it's just an initial implementation - it can be expanded upon easily (poke me on Discord or open a new issue here if you want specific improvements to this).
